# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.28

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/mohammed/CLionProjects/PSF

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/mohammed/CLionProjects/PSF

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target test
test:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running tests..."
	/usr/bin/ctest --force-new-ctest-process $(ARGS)
.PHONY : test

# Special rule for the target test
test/fast: test
.PHONY : test/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Available install components are: \"gmock\" \"gtest\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/mohammed/CLionProjects/PSF/CMakeFiles /home/mohammed/CLionProjects/PSF//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/mohammed/CLionProjects/PSF/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named app

# Build rule for target.
app: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 app
.PHONY : app

# fast build rule for target.
app/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/app.dir/build.make CMakeFiles/app.dir/build
.PHONY : app/fast

#=============================================================================
# Target rules for targets named runUnitTests

# Build rule for target.
runUnitTests: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 runUnitTests
.PHONY : runUnitTests

# fast build rule for target.
runUnitTests/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/runUnitTests.dir/build.make CMakeFiles/runUnitTests.dir/build
.PHONY : runUnitTests/fast

#=============================================================================
# Target rules for targets named gmock

# Build rule for target.
gmock: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 gmock
.PHONY : gmock

# fast build rule for target.
gmock/fast:
	$(MAKE) $(MAKESILENT) -f _deps/googletest-build/googlemock/CMakeFiles/gmock.dir/build.make _deps/googletest-build/googlemock/CMakeFiles/gmock.dir/build
.PHONY : gmock/fast

#=============================================================================
# Target rules for targets named gmock_main

# Build rule for target.
gmock_main: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 gmock_main
.PHONY : gmock_main

# fast build rule for target.
gmock_main/fast:
	$(MAKE) $(MAKESILENT) -f _deps/googletest-build/googlemock/CMakeFiles/gmock_main.dir/build.make _deps/googletest-build/googlemock/CMakeFiles/gmock_main.dir/build
.PHONY : gmock_main/fast

#=============================================================================
# Target rules for targets named gtest

# Build rule for target.
gtest: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 gtest
.PHONY : gtest

# fast build rule for target.
gtest/fast:
	$(MAKE) $(MAKESILENT) -f _deps/googletest-build/googletest/CMakeFiles/gtest.dir/build.make _deps/googletest-build/googletest/CMakeFiles/gtest.dir/build
.PHONY : gtest/fast

#=============================================================================
# Target rules for targets named gtest_main

# Build rule for target.
gtest_main: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 gtest_main
.PHONY : gtest_main

# fast build rule for target.
gtest_main/fast:
	$(MAKE) $(MAKESILENT) -f _deps/googletest-build/googletest/CMakeFiles/gtest_main.dir/build.make _deps/googletest-build/googletest/CMakeFiles/gtest_main.dir/build
.PHONY : gtest_main/fast

Building.o: Building.cpp.o
.PHONY : Building.o

# target to build an object file
Building.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/app.dir/build.make CMakeFiles/app.dir/Building.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/runUnitTests.dir/build.make CMakeFiles/runUnitTests.dir/Building.cpp.o
.PHONY : Building.cpp.o

Building.i: Building.cpp.i
.PHONY : Building.i

# target to preprocess a source file
Building.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/app.dir/build.make CMakeFiles/app.dir/Building.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/runUnitTests.dir/build.make CMakeFiles/runUnitTests.dir/Building.cpp.i
.PHONY : Building.cpp.i

Building.s: Building.cpp.s
.PHONY : Building.s

# target to generate assembly for a file
Building.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/app.dir/build.make CMakeFiles/app.dir/Building.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/runUnitTests.dir/build.make CMakeFiles/runUnitTests.dir/Building.cpp.s
.PHONY : Building.cpp.s

Campus.o: Campus.cpp.o
.PHONY : Campus.o

# target to build an object file
Campus.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/app.dir/build.make CMakeFiles/app.dir/Campus.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/runUnitTests.dir/build.make CMakeFiles/runUnitTests.dir/Campus.cpp.o
.PHONY : Campus.cpp.o

Campus.i: Campus.cpp.i
.PHONY : Campus.i

# target to preprocess a source file
Campus.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/app.dir/build.make CMakeFiles/app.dir/Campus.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/runUnitTests.dir/build.make CMakeFiles/runUnitTests.dir/Campus.cpp.i
.PHONY : Campus.cpp.i

Campus.s: Campus.cpp.s
.PHONY : Campus.s

# target to generate assembly for a file
Campus.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/app.dir/build.make CMakeFiles/app.dir/Campus.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/runUnitTests.dir/build.make CMakeFiles/runUnitTests.dir/Campus.cpp.s
.PHONY : Campus.cpp.s

Catering.o: Catering.cpp.o
.PHONY : Catering.o

# target to build an object file
Catering.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/app.dir/build.make CMakeFiles/app.dir/Catering.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/runUnitTests.dir/build.make CMakeFiles/runUnitTests.dir/Catering.cpp.o
.PHONY : Catering.cpp.o

Catering.i: Catering.cpp.i
.PHONY : Catering.i

# target to preprocess a source file
Catering.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/app.dir/build.make CMakeFiles/app.dir/Catering.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/runUnitTests.dir/build.make CMakeFiles/runUnitTests.dir/Catering.cpp.i
.PHONY : Catering.cpp.i

Catering.s: Catering.cpp.s
.PHONY : Catering.s

# target to generate assembly for a file
Catering.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/app.dir/build.make CMakeFiles/app.dir/Catering.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/runUnitTests.dir/build.make CMakeFiles/runUnitTests.dir/Catering.cpp.s
.PHONY : Catering.cpp.s

Meeting.o: Meeting.cpp.o
.PHONY : Meeting.o

# target to build an object file
Meeting.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/app.dir/build.make CMakeFiles/app.dir/Meeting.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/runUnitTests.dir/build.make CMakeFiles/runUnitTests.dir/Meeting.cpp.o
.PHONY : Meeting.cpp.o

Meeting.i: Meeting.cpp.i
.PHONY : Meeting.i

# target to preprocess a source file
Meeting.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/app.dir/build.make CMakeFiles/app.dir/Meeting.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/runUnitTests.dir/build.make CMakeFiles/runUnitTests.dir/Meeting.cpp.i
.PHONY : Meeting.cpp.i

Meeting.s: Meeting.cpp.s
.PHONY : Meeting.s

# target to generate assembly for a file
Meeting.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/app.dir/build.make CMakeFiles/app.dir/Meeting.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/runUnitTests.dir/build.make CMakeFiles/runUnitTests.dir/Meeting.cpp.s
.PHONY : Meeting.cpp.s

MeetingPlanner.o: MeetingPlanner.cpp.o
.PHONY : MeetingPlanner.o

# target to build an object file
MeetingPlanner.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/app.dir/build.make CMakeFiles/app.dir/MeetingPlanner.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/runUnitTests.dir/build.make CMakeFiles/runUnitTests.dir/MeetingPlanner.cpp.o
.PHONY : MeetingPlanner.cpp.o

MeetingPlanner.i: MeetingPlanner.cpp.i
.PHONY : MeetingPlanner.i

# target to preprocess a source file
MeetingPlanner.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/app.dir/build.make CMakeFiles/app.dir/MeetingPlanner.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/runUnitTests.dir/build.make CMakeFiles/runUnitTests.dir/MeetingPlanner.cpp.i
.PHONY : MeetingPlanner.cpp.i

MeetingPlanner.s: MeetingPlanner.cpp.s
.PHONY : MeetingPlanner.s

# target to generate assembly for a file
MeetingPlanner.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/app.dir/build.make CMakeFiles/app.dir/MeetingPlanner.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/runUnitTests.dir/build.make CMakeFiles/runUnitTests.dir/MeetingPlanner.cpp.s
.PHONY : MeetingPlanner.cpp.s

Participation.o: Participation.cpp.o
.PHONY : Participation.o

# target to build an object file
Participation.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/app.dir/build.make CMakeFiles/app.dir/Participation.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/runUnitTests.dir/build.make CMakeFiles/runUnitTests.dir/Participation.cpp.o
.PHONY : Participation.cpp.o

Participation.i: Participation.cpp.i
.PHONY : Participation.i

# target to preprocess a source file
Participation.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/app.dir/build.make CMakeFiles/app.dir/Participation.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/runUnitTests.dir/build.make CMakeFiles/runUnitTests.dir/Participation.cpp.i
.PHONY : Participation.cpp.i

Participation.s: Participation.cpp.s
.PHONY : Participation.s

# target to generate assembly for a file
Participation.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/app.dir/build.make CMakeFiles/app.dir/Participation.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/runUnitTests.dir/build.make CMakeFiles/runUnitTests.dir/Participation.cpp.s
.PHONY : Participation.cpp.s

Renovation.o: Renovation.cpp.o
.PHONY : Renovation.o

# target to build an object file
Renovation.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/app.dir/build.make CMakeFiles/app.dir/Renovation.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/runUnitTests.dir/build.make CMakeFiles/runUnitTests.dir/Renovation.cpp.o
.PHONY : Renovation.cpp.o

Renovation.i: Renovation.cpp.i
.PHONY : Renovation.i

# target to preprocess a source file
Renovation.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/app.dir/build.make CMakeFiles/app.dir/Renovation.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/runUnitTests.dir/build.make CMakeFiles/runUnitTests.dir/Renovation.cpp.i
.PHONY : Renovation.cpp.i

Renovation.s: Renovation.cpp.s
.PHONY : Renovation.s

# target to generate assembly for a file
Renovation.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/app.dir/build.make CMakeFiles/app.dir/Renovation.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/runUnitTests.dir/build.make CMakeFiles/runUnitTests.dir/Renovation.cpp.s
.PHONY : Renovation.cpp.s

Room.o: Room.cpp.o
.PHONY : Room.o

# target to build an object file
Room.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/app.dir/build.make CMakeFiles/app.dir/Room.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/runUnitTests.dir/build.make CMakeFiles/runUnitTests.dir/Room.cpp.o
.PHONY : Room.cpp.o

Room.i: Room.cpp.i
.PHONY : Room.i

# target to preprocess a source file
Room.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/app.dir/build.make CMakeFiles/app.dir/Room.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/runUnitTests.dir/build.make CMakeFiles/runUnitTests.dir/Room.cpp.i
.PHONY : Room.cpp.i

Room.s: Room.cpp.s
.PHONY : Room.s

# target to generate assembly for a file
Room.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/app.dir/build.make CMakeFiles/app.dir/Room.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/runUnitTests.dir/build.make CMakeFiles/runUnitTests.dir/Room.cpp.s
.PHONY : Room.cpp.s

Test/Building/Test_Building.o: Test/Building/Test_Building.cpp.o
.PHONY : Test/Building/Test_Building.o

# target to build an object file
Test/Building/Test_Building.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/runUnitTests.dir/build.make CMakeFiles/runUnitTests.dir/Test/Building/Test_Building.cpp.o
.PHONY : Test/Building/Test_Building.cpp.o

Test/Building/Test_Building.i: Test/Building/Test_Building.cpp.i
.PHONY : Test/Building/Test_Building.i

# target to preprocess a source file
Test/Building/Test_Building.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/runUnitTests.dir/build.make CMakeFiles/runUnitTests.dir/Test/Building/Test_Building.cpp.i
.PHONY : Test/Building/Test_Building.cpp.i

Test/Building/Test_Building.s: Test/Building/Test_Building.cpp.s
.PHONY : Test/Building/Test_Building.s

# target to generate assembly for a file
Test/Building/Test_Building.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/runUnitTests.dir/build.make CMakeFiles/runUnitTests.dir/Test/Building/Test_Building.cpp.s
.PHONY : Test/Building/Test_Building.cpp.s

Test/Campus/Test_Campus.o: Test/Campus/Test_Campus.cpp.o
.PHONY : Test/Campus/Test_Campus.o

# target to build an object file
Test/Campus/Test_Campus.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/runUnitTests.dir/build.make CMakeFiles/runUnitTests.dir/Test/Campus/Test_Campus.cpp.o
.PHONY : Test/Campus/Test_Campus.cpp.o

Test/Campus/Test_Campus.i: Test/Campus/Test_Campus.cpp.i
.PHONY : Test/Campus/Test_Campus.i

# target to preprocess a source file
Test/Campus/Test_Campus.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/runUnitTests.dir/build.make CMakeFiles/runUnitTests.dir/Test/Campus/Test_Campus.cpp.i
.PHONY : Test/Campus/Test_Campus.cpp.i

Test/Campus/Test_Campus.s: Test/Campus/Test_Campus.cpp.s
.PHONY : Test/Campus/Test_Campus.s

# target to generate assembly for a file
Test/Campus/Test_Campus.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/runUnitTests.dir/build.make CMakeFiles/runUnitTests.dir/Test/Campus/Test_Campus.cpp.s
.PHONY : Test/Campus/Test_Campus.cpp.s

Test/Test.o: Test/Test.cpp.o
.PHONY : Test/Test.o

# target to build an object file
Test/Test.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/runUnitTests.dir/build.make CMakeFiles/runUnitTests.dir/Test/Test.cpp.o
.PHONY : Test/Test.cpp.o

Test/Test.i: Test/Test.cpp.i
.PHONY : Test/Test.i

# target to preprocess a source file
Test/Test.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/runUnitTests.dir/build.make CMakeFiles/runUnitTests.dir/Test/Test.cpp.i
.PHONY : Test/Test.cpp.i

Test/Test.s: Test/Test.cpp.s
.PHONY : Test/Test.s

# target to generate assembly for a file
Test/Test.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/runUnitTests.dir/build.make CMakeFiles/runUnitTests.dir/Test/Test.cpp.s
.PHONY : Test/Test.cpp.s

Test/Test_Meeting.o: Test/Test_Meeting.cpp.o
.PHONY : Test/Test_Meeting.o

# target to build an object file
Test/Test_Meeting.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/runUnitTests.dir/build.make CMakeFiles/runUnitTests.dir/Test/Test_Meeting.cpp.o
.PHONY : Test/Test_Meeting.cpp.o

Test/Test_Meeting.i: Test/Test_Meeting.cpp.i
.PHONY : Test/Test_Meeting.i

# target to preprocess a source file
Test/Test_Meeting.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/runUnitTests.dir/build.make CMakeFiles/runUnitTests.dir/Test/Test_Meeting.cpp.i
.PHONY : Test/Test_Meeting.cpp.i

Test/Test_Meeting.s: Test/Test_Meeting.cpp.s
.PHONY : Test/Test_Meeting.s

# target to generate assembly for a file
Test/Test_Meeting.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/runUnitTests.dir/build.make CMakeFiles/runUnitTests.dir/Test/Test_Meeting.cpp.s
.PHONY : Test/Test_Meeting.cpp.s

Test/Test_MeetingPlanner.o: Test/Test_MeetingPlanner.cpp.o
.PHONY : Test/Test_MeetingPlanner.o

# target to build an object file
Test/Test_MeetingPlanner.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/runUnitTests.dir/build.make CMakeFiles/runUnitTests.dir/Test/Test_MeetingPlanner.cpp.o
.PHONY : Test/Test_MeetingPlanner.cpp.o

Test/Test_MeetingPlanner.i: Test/Test_MeetingPlanner.cpp.i
.PHONY : Test/Test_MeetingPlanner.i

# target to preprocess a source file
Test/Test_MeetingPlanner.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/runUnitTests.dir/build.make CMakeFiles/runUnitTests.dir/Test/Test_MeetingPlanner.cpp.i
.PHONY : Test/Test_MeetingPlanner.cpp.i

Test/Test_MeetingPlanner.s: Test/Test_MeetingPlanner.cpp.s
.PHONY : Test/Test_MeetingPlanner.s

# target to generate assembly for a file
Test/Test_MeetingPlanner.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/runUnitTests.dir/build.make CMakeFiles/runUnitTests.dir/Test/Test_MeetingPlanner.cpp.s
.PHONY : Test/Test_MeetingPlanner.cpp.s

Test/Test_Participation.o: Test/Test_Participation.cpp.o
.PHONY : Test/Test_Participation.o

# target to build an object file
Test/Test_Participation.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/runUnitTests.dir/build.make CMakeFiles/runUnitTests.dir/Test/Test_Participation.cpp.o
.PHONY : Test/Test_Participation.cpp.o

Test/Test_Participation.i: Test/Test_Participation.cpp.i
.PHONY : Test/Test_Participation.i

# target to preprocess a source file
Test/Test_Participation.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/runUnitTests.dir/build.make CMakeFiles/runUnitTests.dir/Test/Test_Participation.cpp.i
.PHONY : Test/Test_Participation.cpp.i

Test/Test_Participation.s: Test/Test_Participation.cpp.s
.PHONY : Test/Test_Participation.s

# target to generate assembly for a file
Test/Test_Participation.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/runUnitTests.dir/build.make CMakeFiles/runUnitTests.dir/Test/Test_Participation.cpp.s
.PHONY : Test/Test_Participation.cpp.s

Test/Test_Renovation.o: Test/Test_Renovation.cpp.o
.PHONY : Test/Test_Renovation.o

# target to build an object file
Test/Test_Renovation.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/runUnitTests.dir/build.make CMakeFiles/runUnitTests.dir/Test/Test_Renovation.cpp.o
.PHONY : Test/Test_Renovation.cpp.o

Test/Test_Renovation.i: Test/Test_Renovation.cpp.i
.PHONY : Test/Test_Renovation.i

# target to preprocess a source file
Test/Test_Renovation.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/runUnitTests.dir/build.make CMakeFiles/runUnitTests.dir/Test/Test_Renovation.cpp.i
.PHONY : Test/Test_Renovation.cpp.i

Test/Test_Renovation.s: Test/Test_Renovation.cpp.s
.PHONY : Test/Test_Renovation.s

# target to generate assembly for a file
Test/Test_Renovation.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/runUnitTests.dir/build.make CMakeFiles/runUnitTests.dir/Test/Test_Renovation.cpp.s
.PHONY : Test/Test_Renovation.cpp.s

Test/Test_XMLreader.o: Test/Test_XMLreader.cpp.o
.PHONY : Test/Test_XMLreader.o

# target to build an object file
Test/Test_XMLreader.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/runUnitTests.dir/build.make CMakeFiles/runUnitTests.dir/Test/Test_XMLreader.cpp.o
.PHONY : Test/Test_XMLreader.cpp.o

Test/Test_XMLreader.i: Test/Test_XMLreader.cpp.i
.PHONY : Test/Test_XMLreader.i

# target to preprocess a source file
Test/Test_XMLreader.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/runUnitTests.dir/build.make CMakeFiles/runUnitTests.dir/Test/Test_XMLreader.cpp.i
.PHONY : Test/Test_XMLreader.cpp.i

Test/Test_XMLreader.s: Test/Test_XMLreader.cpp.s
.PHONY : Test/Test_XMLreader.s

# target to generate assembly for a file
Test/Test_XMLreader.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/runUnitTests.dir/build.make CMakeFiles/runUnitTests.dir/Test/Test_XMLreader.cpp.s
.PHONY : Test/Test_XMLreader.cpp.s

XMLreader.o: XMLreader.cpp.o
.PHONY : XMLreader.o

# target to build an object file
XMLreader.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/app.dir/build.make CMakeFiles/app.dir/XMLreader.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/runUnitTests.dir/build.make CMakeFiles/runUnitTests.dir/XMLreader.cpp.o
.PHONY : XMLreader.cpp.o

XMLreader.i: XMLreader.cpp.i
.PHONY : XMLreader.i

# target to preprocess a source file
XMLreader.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/app.dir/build.make CMakeFiles/app.dir/XMLreader.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/runUnitTests.dir/build.make CMakeFiles/runUnitTests.dir/XMLreader.cpp.i
.PHONY : XMLreader.cpp.i

XMLreader.s: XMLreader.cpp.s
.PHONY : XMLreader.s

# target to generate assembly for a file
XMLreader.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/app.dir/build.make CMakeFiles/app.dir/XMLreader.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/runUnitTests.dir/build.make CMakeFiles/runUnitTests.dir/XMLreader.cpp.s
.PHONY : XMLreader.cpp.s

main.o: main.cpp.o
.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/app.dir/build.make CMakeFiles/app.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i
.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/app.dir/build.make CMakeFiles/app.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s
.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/app.dir/build.make CMakeFiles/app.dir/main.cpp.s
.PHONY : main.cpp.s

tinyxml_2_6_2/tinystr.o: tinyxml_2_6_2/tinystr.cpp.o
.PHONY : tinyxml_2_6_2/tinystr.o

# target to build an object file
tinyxml_2_6_2/tinystr.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/app.dir/build.make CMakeFiles/app.dir/tinyxml_2_6_2/tinystr.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/runUnitTests.dir/build.make CMakeFiles/runUnitTests.dir/tinyxml_2_6_2/tinystr.cpp.o
.PHONY : tinyxml_2_6_2/tinystr.cpp.o

tinyxml_2_6_2/tinystr.i: tinyxml_2_6_2/tinystr.cpp.i
.PHONY : tinyxml_2_6_2/tinystr.i

# target to preprocess a source file
tinyxml_2_6_2/tinystr.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/app.dir/build.make CMakeFiles/app.dir/tinyxml_2_6_2/tinystr.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/runUnitTests.dir/build.make CMakeFiles/runUnitTests.dir/tinyxml_2_6_2/tinystr.cpp.i
.PHONY : tinyxml_2_6_2/tinystr.cpp.i

tinyxml_2_6_2/tinystr.s: tinyxml_2_6_2/tinystr.cpp.s
.PHONY : tinyxml_2_6_2/tinystr.s

# target to generate assembly for a file
tinyxml_2_6_2/tinystr.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/app.dir/build.make CMakeFiles/app.dir/tinyxml_2_6_2/tinystr.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/runUnitTests.dir/build.make CMakeFiles/runUnitTests.dir/tinyxml_2_6_2/tinystr.cpp.s
.PHONY : tinyxml_2_6_2/tinystr.cpp.s

tinyxml_2_6_2/tinyxml.o: tinyxml_2_6_2/tinyxml.cpp.o
.PHONY : tinyxml_2_6_2/tinyxml.o

# target to build an object file
tinyxml_2_6_2/tinyxml.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/app.dir/build.make CMakeFiles/app.dir/tinyxml_2_6_2/tinyxml.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/runUnitTests.dir/build.make CMakeFiles/runUnitTests.dir/tinyxml_2_6_2/tinyxml.cpp.o
.PHONY : tinyxml_2_6_2/tinyxml.cpp.o

tinyxml_2_6_2/tinyxml.i: tinyxml_2_6_2/tinyxml.cpp.i
.PHONY : tinyxml_2_6_2/tinyxml.i

# target to preprocess a source file
tinyxml_2_6_2/tinyxml.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/app.dir/build.make CMakeFiles/app.dir/tinyxml_2_6_2/tinyxml.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/runUnitTests.dir/build.make CMakeFiles/runUnitTests.dir/tinyxml_2_6_2/tinyxml.cpp.i
.PHONY : tinyxml_2_6_2/tinyxml.cpp.i

tinyxml_2_6_2/tinyxml.s: tinyxml_2_6_2/tinyxml.cpp.s
.PHONY : tinyxml_2_6_2/tinyxml.s

# target to generate assembly for a file
tinyxml_2_6_2/tinyxml.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/app.dir/build.make CMakeFiles/app.dir/tinyxml_2_6_2/tinyxml.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/runUnitTests.dir/build.make CMakeFiles/runUnitTests.dir/tinyxml_2_6_2/tinyxml.cpp.s
.PHONY : tinyxml_2_6_2/tinyxml.cpp.s

tinyxml_2_6_2/tinyxmlerror.o: tinyxml_2_6_2/tinyxmlerror.cpp.o
.PHONY : tinyxml_2_6_2/tinyxmlerror.o

# target to build an object file
tinyxml_2_6_2/tinyxmlerror.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/app.dir/build.make CMakeFiles/app.dir/tinyxml_2_6_2/tinyxmlerror.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/runUnitTests.dir/build.make CMakeFiles/runUnitTests.dir/tinyxml_2_6_2/tinyxmlerror.cpp.o
.PHONY : tinyxml_2_6_2/tinyxmlerror.cpp.o

tinyxml_2_6_2/tinyxmlerror.i: tinyxml_2_6_2/tinyxmlerror.cpp.i
.PHONY : tinyxml_2_6_2/tinyxmlerror.i

# target to preprocess a source file
tinyxml_2_6_2/tinyxmlerror.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/app.dir/build.make CMakeFiles/app.dir/tinyxml_2_6_2/tinyxmlerror.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/runUnitTests.dir/build.make CMakeFiles/runUnitTests.dir/tinyxml_2_6_2/tinyxmlerror.cpp.i
.PHONY : tinyxml_2_6_2/tinyxmlerror.cpp.i

tinyxml_2_6_2/tinyxmlerror.s: tinyxml_2_6_2/tinyxmlerror.cpp.s
.PHONY : tinyxml_2_6_2/tinyxmlerror.s

# target to generate assembly for a file
tinyxml_2_6_2/tinyxmlerror.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/app.dir/build.make CMakeFiles/app.dir/tinyxml_2_6_2/tinyxmlerror.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/runUnitTests.dir/build.make CMakeFiles/runUnitTests.dir/tinyxml_2_6_2/tinyxmlerror.cpp.s
.PHONY : tinyxml_2_6_2/tinyxmlerror.cpp.s

tinyxml_2_6_2/tinyxmlparser.o: tinyxml_2_6_2/tinyxmlparser.cpp.o
.PHONY : tinyxml_2_6_2/tinyxmlparser.o

# target to build an object file
tinyxml_2_6_2/tinyxmlparser.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/app.dir/build.make CMakeFiles/app.dir/tinyxml_2_6_2/tinyxmlparser.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/runUnitTests.dir/build.make CMakeFiles/runUnitTests.dir/tinyxml_2_6_2/tinyxmlparser.cpp.o
.PHONY : tinyxml_2_6_2/tinyxmlparser.cpp.o

tinyxml_2_6_2/tinyxmlparser.i: tinyxml_2_6_2/tinyxmlparser.cpp.i
.PHONY : tinyxml_2_6_2/tinyxmlparser.i

# target to preprocess a source file
tinyxml_2_6_2/tinyxmlparser.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/app.dir/build.make CMakeFiles/app.dir/tinyxml_2_6_2/tinyxmlparser.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/runUnitTests.dir/build.make CMakeFiles/runUnitTests.dir/tinyxml_2_6_2/tinyxmlparser.cpp.i
.PHONY : tinyxml_2_6_2/tinyxmlparser.cpp.i

tinyxml_2_6_2/tinyxmlparser.s: tinyxml_2_6_2/tinyxmlparser.cpp.s
.PHONY : tinyxml_2_6_2/tinyxmlparser.s

# target to generate assembly for a file
tinyxml_2_6_2/tinyxmlparser.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/app.dir/build.make CMakeFiles/app.dir/tinyxml_2_6_2/tinyxmlparser.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/runUnitTests.dir/build.make CMakeFiles/runUnitTests.dir/tinyxml_2_6_2/tinyxmlparser.cpp.s
.PHONY : tinyxml_2_6_2/tinyxmlparser.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... test"
	@echo "... app"
	@echo "... gmock"
	@echo "... gmock_main"
	@echo "... gtest"
	@echo "... gtest_main"
	@echo "... runUnitTests"
	@echo "... Building.o"
	@echo "... Building.i"
	@echo "... Building.s"
	@echo "... Campus.o"
	@echo "... Campus.i"
	@echo "... Campus.s"
	@echo "... Catering.o"
	@echo "... Catering.i"
	@echo "... Catering.s"
	@echo "... Meeting.o"
	@echo "... Meeting.i"
	@echo "... Meeting.s"
	@echo "... MeetingPlanner.o"
	@echo "... MeetingPlanner.i"
	@echo "... MeetingPlanner.s"
	@echo "... Participation.o"
	@echo "... Participation.i"
	@echo "... Participation.s"
	@echo "... Renovation.o"
	@echo "... Renovation.i"
	@echo "... Renovation.s"
	@echo "... Room.o"
	@echo "... Room.i"
	@echo "... Room.s"
	@echo "... Test/Building/Test_Building.o"
	@echo "... Test/Building/Test_Building.i"
	@echo "... Test/Building/Test_Building.s"
	@echo "... Test/Campus/Test_Campus.o"
	@echo "... Test/Campus/Test_Campus.i"
	@echo "... Test/Campus/Test_Campus.s"
	@echo "... Test/Test.o"
	@echo "... Test/Test.i"
	@echo "... Test/Test.s"
	@echo "... Test/Test_Meeting.o"
	@echo "... Test/Test_Meeting.i"
	@echo "... Test/Test_Meeting.s"
	@echo "... Test/Test_MeetingPlanner.o"
	@echo "... Test/Test_MeetingPlanner.i"
	@echo "... Test/Test_MeetingPlanner.s"
	@echo "... Test/Test_Participation.o"
	@echo "... Test/Test_Participation.i"
	@echo "... Test/Test_Participation.s"
	@echo "... Test/Test_Renovation.o"
	@echo "... Test/Test_Renovation.i"
	@echo "... Test/Test_Renovation.s"
	@echo "... Test/Test_XMLreader.o"
	@echo "... Test/Test_XMLreader.i"
	@echo "... Test/Test_XMLreader.s"
	@echo "... XMLreader.o"
	@echo "... XMLreader.i"
	@echo "... XMLreader.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... tinyxml_2_6_2/tinystr.o"
	@echo "... tinyxml_2_6_2/tinystr.i"
	@echo "... tinyxml_2_6_2/tinystr.s"
	@echo "... tinyxml_2_6_2/tinyxml.o"
	@echo "... tinyxml_2_6_2/tinyxml.i"
	@echo "... tinyxml_2_6_2/tinyxml.s"
	@echo "... tinyxml_2_6_2/tinyxmlerror.o"
	@echo "... tinyxml_2_6_2/tinyxmlerror.i"
	@echo "... tinyxml_2_6_2/tinyxmlerror.s"
	@echo "... tinyxml_2_6_2/tinyxmlparser.o"
	@echo "... tinyxml_2_6_2/tinyxmlparser.i"
	@echo "... tinyxml_2_6_2/tinyxmlparser.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

