add_test([=[RoomTest.ValidRoom]=]  /home/mohammed/CLionProjects/PSF/runUnitTests [==[--gtest_filter=RoomTest.ValidRoom]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[RoomTest.ValidRoom]=]  PROPERTIES WORKING_DIRECTORY /home/mohammed/CLionProjects/PSF SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[RoomTest.EmptyName]=]  /home/mohammed/CLionProjects/PSF/runUnitTests [==[--gtest_filter=RoomTest.EmptyName]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[RoomTest.EmptyName]=]  PROPERTIES WORKING_DIRECTORY /home/mohammed/CLionProjects/PSF SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[RoomTest.EmptyIdentifier]=]  /home/mohammed/CLionProjects/PSF/runUnitTests [==[--gtest_filter=RoomTest.EmptyIdentifier]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[RoomTest.EmptyIdentifier]=]  PROPERTIES WORKING_DIRECTORY /home/mohammed/CLionProjects/PSF SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[RoomTest.InvalidCapacity]=]  /home/mohammed/CLionProjects/PSF/runUnitTests [==[--gtest_filter=RoomTest.InvalidCapacity]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[RoomTest.InvalidCapacity]=]  PROPERTIES WORKING_DIRECTORY /home/mohammed/CLionProjects/PSF SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[RoomTest.NegativeCapacity]=]  /home/mohammed/CLionProjects/PSF/runUnitTests [==[--gtest_filter=RoomTest.NegativeCapacity]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[RoomTest.NegativeCapacity]=]  PROPERTIES WORKING_DIRECTORY /home/mohammed/CLionProjects/PSF SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[MeetingTest.TestGetLabel]=]  /home/mohammed/CLionProjects/PSF/runUnitTests [==[--gtest_filter=MeetingTest.TestGetLabel]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[MeetingTest.TestGetLabel]=]  PROPERTIES WORKING_DIRECTORY /home/mohammed/CLionProjects/PSF SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[MeetingTest.TestGetIdentifier]=]  /home/mohammed/CLionProjects/PSF/runUnitTests [==[--gtest_filter=MeetingTest.TestGetIdentifier]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[MeetingTest.TestGetIdentifier]=]  PROPERTIES WORKING_DIRECTORY /home/mohammed/CLionProjects/PSF SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[MeetingTest.TestGetRoom]=]  /home/mohammed/CLionProjects/PSF/runUnitTests [==[--gtest_filter=MeetingTest.TestGetRoom]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[MeetingTest.TestGetRoom]=]  PROPERTIES WORKING_DIRECTORY /home/mohammed/CLionProjects/PSF SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[MeetingTest.TestSetLabel]=]  /home/mohammed/CLionProjects/PSF/runUnitTests [==[--gtest_filter=MeetingTest.TestSetLabel]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[MeetingTest.TestSetLabel]=]  PROPERTIES WORKING_DIRECTORY /home/mohammed/CLionProjects/PSF SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[MeetingTest.TestSetIdentifier]=]  /home/mohammed/CLionProjects/PSF/runUnitTests [==[--gtest_filter=MeetingTest.TestSetIdentifier]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[MeetingTest.TestSetIdentifier]=]  PROPERTIES WORKING_DIRECTORY /home/mohammed/CLionProjects/PSF SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[MeetingPlannerTest.TestAddRoom]=]  /home/mohammed/CLionProjects/PSF/runUnitTests [==[--gtest_filter=MeetingPlannerTest.TestAddRoom]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[MeetingPlannerTest.TestAddRoom]=]  PROPERTIES WORKING_DIRECTORY /home/mohammed/CLionProjects/PSF SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[MeetingPlannerTest.TestFindRoom]=]  /home/mohammed/CLionProjects/PSF/runUnitTests [==[--gtest_filter=MeetingPlannerTest.TestFindRoom]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[MeetingPlannerTest.TestFindRoom]=]  PROPERTIES WORKING_DIRECTORY /home/mohammed/CLionProjects/PSF SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[MeetingPlannerTest.TestAddMeeting]=]  /home/mohammed/CLionProjects/PSF/runUnitTests [==[--gtest_filter=MeetingPlannerTest.TestAddMeeting]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[MeetingPlannerTest.TestAddMeeting]=]  PROPERTIES WORKING_DIRECTORY /home/mohammed/CLionProjects/PSF SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[MeetingPlannerTest.TestAddParticipation]=]  /home/mohammed/CLionProjects/PSF/runUnitTests [==[--gtest_filter=MeetingPlannerTest.TestAddParticipation]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[MeetingPlannerTest.TestAddParticipation]=]  PROPERTIES WORKING_DIRECTORY /home/mohammed/CLionProjects/PSF SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[MeetingPlannerTest.TestInconsistentCapacity]=]  /home/mohammed/CLionProjects/PSF/runUnitTests [==[--gtest_filter=MeetingPlannerTest.TestInconsistentCapacity]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[MeetingPlannerTest.TestInconsistentCapacity]=]  PROPERTIES WORKING_DIRECTORY /home/mohammed/CLionProjects/PSF SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[MeetingPlannerTest.TestAddMeetingDuringRenovationThrows]=]  /home/mohammed/CLionProjects/PSF/runUnitTests [==[--gtest_filter=MeetingPlannerTest.TestAddMeetingDuringRenovationThrows]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[MeetingPlannerTest.TestAddMeetingDuringRenovationThrows]=]  PROPERTIES WORKING_DIRECTORY /home/mohammed/CLionProjects/PSF SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[MeetingPlannerTest.TestMeetingOutsideRenovation]=]  /home/mohammed/CLionProjects/PSF/runUnitTests [==[--gtest_filter=MeetingPlannerTest.TestMeetingOutsideRenovation]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[MeetingPlannerTest.TestMeetingOutsideRenovation]=]  PROPERTIES WORKING_DIRECTORY /home/mohammed/CLionProjects/PSF SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[ParticipationTest.TestGetUser]=]  /home/mohammed/CLionProjects/PSF/runUnitTests [==[--gtest_filter=ParticipationTest.TestGetUser]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[ParticipationTest.TestGetUser]=]  PROPERTIES WORKING_DIRECTORY /home/mohammed/CLionProjects/PSF SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[ParticipationTest.TestGetMeetingIdentifier]=]  /home/mohammed/CLionProjects/PSF/runUnitTests [==[--gtest_filter=ParticipationTest.TestGetMeetingIdentifier]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[ParticipationTest.TestGetMeetingIdentifier]=]  PROPERTIES WORKING_DIRECTORY /home/mohammed/CLionProjects/PSF SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[ParticipationTest.TestSetUser]=]  /home/mohammed/CLionProjects/PSF/runUnitTests [==[--gtest_filter=ParticipationTest.TestSetUser]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[ParticipationTest.TestSetUser]=]  PROPERTIES WORKING_DIRECTORY /home/mohammed/CLionProjects/PSF SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[ParticipationTest.TestSetMeeting]=]  /home/mohammed/CLionProjects/PSF/runUnitTests [==[--gtest_filter=ParticipationTest.TestSetMeeting]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[ParticipationTest.TestSetMeeting]=]  PROPERTIES WORKING_DIRECTORY /home/mohammed/CLionProjects/PSF SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[XMLreaderTest.TestReadValidFile]=]  /home/mohammed/CLionProjects/PSF/runUnitTests [==[--gtest_filter=XMLreaderTest.TestReadValidFile]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[XMLreaderTest.TestReadValidFile]=]  PROPERTIES WORKING_DIRECTORY /home/mohammed/CLionProjects/PSF SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[XMLreaderTest.TestFileNotFound]=]  /home/mohammed/CLionProjects/PSF/runUnitTests [==[--gtest_filter=XMLreaderTest.TestFileNotFound]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[XMLreaderTest.TestFileNotFound]=]  PROPERTIES WORKING_DIRECTORY /home/mohammed/CLionProjects/PSF SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[RenovationTest.TestGetRoomId]=]  /home/mohammed/CLionProjects/PSF/runUnitTests [==[--gtest_filter=RenovationTest.TestGetRoomId]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[RenovationTest.TestGetRoomId]=]  PROPERTIES WORKING_DIRECTORY /home/mohammed/CLionProjects/PSF SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[RenovationTest.TestGetStartDate]=]  /home/mohammed/CLionProjects/PSF/runUnitTests [==[--gtest_filter=RenovationTest.TestGetStartDate]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[RenovationTest.TestGetStartDate]=]  PROPERTIES WORKING_DIRECTORY /home/mohammed/CLionProjects/PSF SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[RenovationTest.TestGetEndDate]=]  /home/mohammed/CLionProjects/PSF/runUnitTests [==[--gtest_filter=RenovationTest.TestGetEndDate]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[RenovationTest.TestGetEndDate]=]  PROPERTIES WORKING_DIRECTORY /home/mohammed/CLionProjects/PSF SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[RenovationTest.TestSameStartAndEndDate]=]  /home/mohammed/CLionProjects/PSF/runUnitTests [==[--gtest_filter=RenovationTest.TestSameStartAndEndDate]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[RenovationTest.TestSameStartAndEndDate]=]  PROPERTIES WORKING_DIRECTORY /home/mohammed/CLionProjects/PSF SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[BuildingTest.TestConstructorAndGetters]=]  /home/mohammed/CLionProjects/PSF/runUnitTests [==[--gtest_filter=BuildingTest.TestConstructorAndGetters]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[BuildingTest.TestConstructorAndGetters]=]  PROPERTIES WORKING_DIRECTORY /home/mohammed/CLionProjects/PSF SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[BuildingTest.TestSetName]=]  /home/mohammed/CLionProjects/PSF/runUnitTests [==[--gtest_filter=BuildingTest.TestSetName]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[BuildingTest.TestSetName]=]  PROPERTIES WORKING_DIRECTORY /home/mohammed/CLionProjects/PSF SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[BuildingTest.TestSetIdentifier]=]  /home/mohammed/CLionProjects/PSF/runUnitTests [==[--gtest_filter=BuildingTest.TestSetIdentifier]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[BuildingTest.TestSetIdentifier]=]  PROPERTIES WORKING_DIRECTORY /home/mohammed/CLionProjects/PSF SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[BuildingTest.TestSetCampusIdentifier]=]  /home/mohammed/CLionProjects/PSF/runUnitTests [==[--gtest_filter=BuildingTest.TestSetCampusIdentifier]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[BuildingTest.TestSetCampusIdentifier]=]  PROPERTIES WORKING_DIRECTORY /home/mohammed/CLionProjects/PSF SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[BuildingTest.TestDefaultConstructor]=]  /home/mohammed/CLionProjects/PSF/runUnitTests [==[--gtest_filter=BuildingTest.TestDefaultConstructor]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[BuildingTest.TestDefaultConstructor]=]  PROPERTIES WORKING_DIRECTORY /home/mohammed/CLionProjects/PSF SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[CampusTest.TestConstructorAndGetters]=]  /home/mohammed/CLionProjects/PSF/runUnitTests [==[--gtest_filter=CampusTest.TestConstructorAndGetters]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[CampusTest.TestConstructorAndGetters]=]  PROPERTIES WORKING_DIRECTORY /home/mohammed/CLionProjects/PSF SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[CampusTest.TestSetName]=]  /home/mohammed/CLionProjects/PSF/runUnitTests [==[--gtest_filter=CampusTest.TestSetName]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[CampusTest.TestSetName]=]  PROPERTIES WORKING_DIRECTORY /home/mohammed/CLionProjects/PSF SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[CampusTest.TestSetIdentifier]=]  /home/mohammed/CLionProjects/PSF/runUnitTests [==[--gtest_filter=CampusTest.TestSetIdentifier]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[CampusTest.TestSetIdentifier]=]  PROPERTIES WORKING_DIRECTORY /home/mohammed/CLionProjects/PSF SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[CampusTest.TestDefaultConstructor]=]  /home/mohammed/CLionProjects/PSF/runUnitTests [==[--gtest_filter=CampusTest.TestDefaultConstructor]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[CampusTest.TestDefaultConstructor]=]  PROPERTIES WORKING_DIRECTORY /home/mohammed/CLionProjects/PSF SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
set(  runUnitTests_TESTS RoomTest.ValidRoom RoomTest.EmptyName RoomTest.EmptyIdentifier RoomTest.InvalidCapacity RoomTest.NegativeCapacity MeetingTest.TestGetLabel MeetingTest.TestGetIdentifier MeetingTest.TestGetRoom MeetingTest.TestSetLabel MeetingTest.TestSetIdentifier MeetingPlannerTest.TestAddRoom MeetingPlannerTest.TestFindRoom MeetingPlannerTest.TestAddMeeting MeetingPlannerTest.TestAddParticipation MeetingPlannerTest.TestInconsistentCapacity MeetingPlannerTest.TestAddMeetingDuringRenovationThrows MeetingPlannerTest.TestMeetingOutsideRenovation ParticipationTest.TestGetUser ParticipationTest.TestGetMeetingIdentifier ParticipationTest.TestSetUser ParticipationTest.TestSetMeeting XMLreaderTest.TestReadValidFile XMLreaderTest.TestFileNotFound RenovationTest.TestGetRoomId RenovationTest.TestGetStartDate RenovationTest.TestGetEndDate RenovationTest.TestSameStartAndEndDate BuildingTest.TestConstructorAndGetters BuildingTest.TestSetName BuildingTest.TestSetIdentifier BuildingTest.TestSetCampusIdentifier BuildingTest.TestDefaultConstructor CampusTest.TestConstructorAndGetters CampusTest.TestSetName CampusTest.TestSetIdentifier CampusTest.TestDefaultConstructor)
